module GTK
  class Layout

    attr_reader row_count: Integer
    attr_reader row_max_index: Integer
    attr_reader col_count: Integer
    attr_reader col_max_index: Integer
    attr_reader gutter_height: Numeric
    attr_reader gutter_width: Numeric
    attr_reader cell_height: Numeric
    attr_reader cell_width: Numeric

    def rect: (
        ?row: Integer,
        ?col: Integer,
        ?w: Integer,
        ?h: Integer,
        ?row_from_bottom: Integer?,
        ?col_from_right: Integer?,
        ?max_width: Integer?,
        ?max_height: Integer?,
        ?dx: Integer,
        ?dy: Integer,
        ?include_row_gutter: bool,
        ?include_col_gutter: bool,
        ?merge: Hash[Symbol, untyped]?,
        ?origin: Symbol,
        ?safe_area: bool
      ) -> {
        x: Integer,
        y: Integer,
        w: Integer,
        h: Integer,
        center_x: Integer,
        center_y: Integer,
        center: {
            x: Integer,
            y: Integer,
          }
      }

    def debug_primitives: (?invert_colors: bool) -> Array[untyped]

    def landscape?: () -> bool

    def portrait?: () -> bool
  end
end
